### ISSUE TITLE
Can’t register

### ISSUE THREAD

**Issue by szony97** [ERap320/LenovoWatchMOD#22]
I can’t register a new account, the verification email is not sent. Also can’t upgrade the versiin of my watch even tough there is an update.

**Comment by erap320** [comment]
I just released version [3.1.7](https://github.com/ERap320/LenovoWatchMOD/releases/tag/3.1.7), can you check if the problem is also there in the new one?
And if it doesn't work could you also try with the original application to see if the problem is limited to the mod?

**Comment by szony97** [comment]
Sadly it’s still not working. And it does not work on the original app either, so its not just in the mod.
